export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_WAITING = "waiting";
export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_DRAFT = "draft";
export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_CONFIRMED = "confirmed";
export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_REJECTED = "rejected";
export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_EMPTY = "empty";

export const CALENDAR_APPROVAL_STATUS_MNEMOCODE_LIST = [
  CALENDAR_APPROVAL_STATUS_MNEMOCODE_WAITING,
  CALENDAR_APPROVAL_STATUS_MNEMOCODE_DRAFT,
  CALENDAR_APPROVAL_STATUS_MNEMOCODE_CONFIRMED,
  CALENDAR_APPROVAL_STATUS_MNEMOCODE_REJECTED,
];

// Мнемокоды действий при пересечении смен
export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_SPECIFIED = "not_specified";
export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_CREATE = "not_create";
export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_DELETE_AND_CREATE = "delete_and_create";
export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_CREATE_WITH_OVERLAPPING = "create_with_overlapping";
export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_DELETE_AND_CREATE_SKIP_WITH_FACT =
  "delete_and_create_skip_with_fact";

export const CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_LIST = [
  CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_SPECIFIED,
  CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_CREATE,
  CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_DELETE_AND_CREATE,
  CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_CREATE_WITH_OVERLAPPING,
  CALENDAR_ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_DELETE_AND_CREATE_SKIP_WITH_FACT,
];
