export const ORGSTRUCTURAL_TYPE_MNEMOCODE_TRADING_POINT = "trading_point";
export const ORGSTRUCTURAL_TYPE_MNEMOCODE_ORGSTRUCTURAL_UNIT = "orgstructural_unit";

export const ORGSTRUCTURAL_TYPE_MNEMOCODE_LIST = [
  ORGSTRUCTURAL_TYPE_MNEMOCODE_TRADING_POINT,
  ORGSTRUCTURAL_TYPE_MNEMOCODE_ORGSTRUCTURAL_UNIT,
];
