export const ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_SPECIFIED = "not_specified";
export const ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_NOT_CREATE = "not_create";
export const ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_DELETE_AND_CREATE = "delete_and_create";
export const ACTION_REQUIRED_OVERLAPPING_MNEMOCODE_CREATE_WITH_OVERLAPPING = "create_with_overlapping";
