export const TIME_TABLE_TEMPLATE_APPLY_TYPE_MNEMOCODE_WEEK_DAYS = "week_days";
export const TIME_TABLE_TEMPLATE_APPLY_TYPE_MNEMOCODE_DAYS_ON_OFF = "days_on_off";

export const TIME_TABLE_TEMPLATE_APPLY_TYPE_MNEMOCODE_LIST = [
  TIME_TABLE_TEMPLATE_APPLY_TYPE_MNEMOCODE_WEEK_DAYS,
  TIME_TABLE_TEMPLATE_APPLY_TYPE_MNEMOCODE_DAYS_ON_OFF,
];

export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_MON = "mon";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_TUE = "tue";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_WED = "wed";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_THU = "thu";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_FRI = "fri";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_SAT = "sat";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_SUN = "sun";

export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_LIST_WEEK_DAYS = [
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_MON,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_TUE,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_WED,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_THU,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_FRI,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_SAT,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_SUN,
];

export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_1 = "days_on_off_1";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_2 = "days_on_off_2";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_3 = "days_on_off_3";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_4 = "days_on_off_4";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_5 = "days_on_off_5";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_6 = "days_on_off_6";
export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_7 = "days_on_off_7";

export const TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_LIST_DAYS_ON_OFF = [
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_1,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_2,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_3,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_4,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_5,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_6,
  TIME_TABLE_TEMPLATE_CELL_DAY_INFO_MNEMOCODE_DAYS_ON_OFF_7,
];
