export const USR_ACC_SYS_ROLE_JSON_ADMIN = "admin";
export const USR_ACC_SYS_ROLE_JSON_TOWN_EDITOR = "town_editor";
export const USR_ACC_SYS_ROLE_JSON_STAKEHOLDER_EDITOR = "stakeholder_editor";
export const USR_ACC_SYS_ROLE_JSON_SYS_OPTION_EDITOR = "sys_option_editor";

export const USR_ACC_AVA_MAX_SIZE_IN_BYTE = 8000000;

export const USR_ACC_SYS_ROLE_JSON_LIST = [
  USR_ACC_SYS_ROLE_JSON_ADMIN,
  USR_ACC_SYS_ROLE_JSON_TOWN_EDITOR,
  USR_ACC_SYS_ROLE_JSON_STAKEHOLDER_EDITOR,
  USR_ACC_SYS_ROLE_JSON_SYS_OPTION_EDITOR,
];

export const USR_ACC_GENDER_MNEMOCODE_MALE = "M";
export const USR_ACC_GENDER_MNEMOCODE_FEMALE = "F";
export const USR_ACC_GENDER_MNEMOCODE_EMPTY = "";

export const USR_ACC_GENDER_MNEMOCODE_LIST = [
  USR_ACC_GENDER_MNEMOCODE_MALE, //
  USR_ACC_GENDER_MNEMOCODE_FEMALE,
  USR_ACC_GENDER_MNEMOCODE_EMPTY,
];

export const USR_ACC_TWO_FACTOR_MNEMOCODE_SMS = "SMS";
export const USR_ACC_TWO_FACTOR_MNEMOCODE_EMAIL = "EMAIL";
export const USR_ACC_TWO_FACTOR_MNEMOCODE_EMPTY = "";

export const USR_ACC_TWO_FACTOR_MNEMOCODE_LIST = [
  USR_ACC_TWO_FACTOR_MNEMOCODE_SMS, //
  USR_ACC_TWO_FACTOR_MNEMOCODE_EMAIL,
  USR_ACC_TWO_FACTOR_MNEMOCODE_EMPTY,
];
