export const MAX_DURATION_OF_ATTEMPT_MINUTES = 5;

export const IDENTIFICATION_MOMENT_MNEMOCODE_START_MOMENT = "start_moment";
export const IDENTIFICATION_MOMENT_MNEMOCODE_FINISH_MOMENT = "finish_moment";

export const IDENTIFICATION_MOMENT_MNEMOCODE_LIST = [
  IDENTIFICATION_MOMENT_MNEMOCODE_START_MOMENT,
  IDENTIFICATION_MOMENT_MNEMOCODE_FINISH_MOMENT,
];

export const FAKE_AUTO_CHECK_STATUS_MNEMOCODE_IN_PROCESS = "in_process";
export const FAKE_AUTO_CHECK_STATUS_MNEMOCODE_NOT_SUSPECTED = "not_suspected";
export const FAKE_AUTO_CHECK_STATUS_MNEMOCODE_SUSPICION = "suspicion";

export const FAKE_AUTO_CHECK_STATUS_MNEMOCODE_LIST = [
  FAKE_AUTO_CHECK_STATUS_MNEMOCODE_IN_PROCESS,
  FAKE_AUTO_CHECK_STATUS_MNEMOCODE_NOT_SUSPECTED,
  FAKE_AUTO_CHECK_STATUS_MNEMOCODE_SUSPICION,
];

export const FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_NO_ACTION_REQUIRED = "no_action_required";
export const FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_DECISION_REQUIRED = "decision_required";
export const FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_CREDIBLE = "credible";
export const FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_CONFIRMED_FAKE = "confirmed_fake";

export const FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_LIST = [
  FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_NO_ACTION_REQUIRED,
  FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_DECISION_REQUIRED,
  FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_CREDIBLE,
  FAKE_MANUAL_CHECK_STATUS_MNEMOCODE_CONFIRMED_FAKE,
];
